name: Render Double Resume

on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  #only support 3.12+ for rendercv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render Chinese CV
        run: rendercv render wangxin_ch.yaml_CV.yaml

      - name: Render English CV
        run: rendercv render wangxin_en.yaml_CV.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rendercv_output
          force_orphan: true
